# -*- coding: utf-8 -*-
stages:
  extract:
    cmd: python3 -m scripts.extract.extract
    params:
    - extract
    deps:
    - ./scripts/extract/
    outs:
    - ./dataset_raw/
    frozen: true

  prepare:
    cmd: python3 -m scripts.preprocessing.prepare
    params:
    - prepare
    deps:
    - ./dataset_raw/
    - ./scripts/preprocessing/prepare.py
    outs:
    - ./dataset/

  train_simclr:
    cmd: python3 -m scripts.model.train_simclr
    params:
    - data
    - train_simclr
    deps:
    - ./dataset/
    - ./dataset_raw/
    - ./scripts/model/train_simclr.py
    - ./scripts/model/resnet.py
    - ./scripts/model/resnet_simclr.py
    - ./scripts/model/losses.py
    outs:
    - ./model/resnet.pt

  train_cinn:
    cmd: python3 -m scripts.model.train_cinn
    params:
    - data
    - train_cinn
    deps:
    - ./dataset/
    - ./dataset_raw/
    - ./scripts/model/
    outs:
    - ./model/cinn_*

  write_representation:
    cmd: python3 -m scripts.postprocessing.write_representation
    deps:
    - ./scripts/postprocessing/write_representation.py
    - ./model/resnet.pt
    - ./dataset_raw/
    - ./dataset/
    outs:
    - ./postprocessing/representation.npy

  create_UMAP:
    cmd: python3 -m scripts.postprocessing.create_UMAP
    deps:
    - ./scripts/postprocessing/create_UMAP.py
    - ./postprocessing/representation.npy
    outs:
    - ./postprocessing/umap.npy
